site_name: Wen-hung Chou's personal website
site_url: https://WHChou.github.io/
theme:
  name: material
  custom_dir: overrides
  palette:
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple 
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Helvetica
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: material/book-open

nav:
  - Home: index.md
  - Projects: projects.md
  - CV: cv.md
  - Contact: contact.md

not_in_nav: 
  Projects/*
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wenhungchou/
    - icon: fontawesome/brands/github
      link: https://github.com/WHChou
    - icon: fontawesome/solid/envelope
      link: mailto:whchou29@gmail.com
  analytics:
    provider: google
    property: G-H96961D5NP
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
extra_css:
  - stylesheets/extra.css
